[package]
name = "bellman-sha256"
version = "0.1.0"
authors = ["Long Wen <longwen6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bellman = "0.6.0"
pairing = "0.16.0"
rand = "0.7.3"
sha2 = "0.8.1"
